# Basic
title: xin-个人站
subtitle: 博客站
description: hello friend
# 头像里面的标题
avatarTitle: xin2233
# 头像里面的描述
avatarDesc: 偶爾記錄一些疑難問題~~
url: "http://xin2233.github.io"

# 博客是否自动生成目录，false为不生成
enableToc: true

# Comment
comment:
    # livere: MTAyMC81MDk5NC8yNzQ3Ng  # https://www.livere.com
    # disqus: leopard
    # uyan: 2143225  # 有言id,登录有言官网申请

# Social
social:
    # weibo: 5366874726 
    github: xin2233
    # zhihu: panpanleopard
    # juejin: xxx
    # jianshu: 2ada30d8d0f7
    # twitter: 
    mail: foreverxr@qq.com


# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    # id: 8ba1c6be0953b6f9c2ba38e57f615421  

# Google Analytics
# 使用博客模板请去掉或者更换 id
# ga:
    # id: UA-84134159-3  
    # host: auto  


# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#  _post/ 下的文章更换成你自己的文章
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 技术支持, description: support, url: '/support'}      
    - {title: 关于我, description: about, url: '/about'}   
    
plugins: [jekyll-feed, jekyll-paginate, jekyll-sitemap]

# Pagination
# gems: [jekyll-sitemap]  # 因爲bundler 升級到4.2.2 此處屏蔽了以後才會正常，原因沒有深入研究。
paginate: 20
paginate_path: "page/:num/"


